services:
  backend:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    container_name: backend
    ports:
      - "5000:5000"
    environment:
        DB_NAME: datacenter_management
        DB_USER: postgres
        DB_PASSWORD: postgres
        DB_HOST: db
        DB_PORT: 5432
        PORT: 5000
    restart: unless-stopped
    networks:
      - my_network
    depends_on:
      - db

  db:
    build:
      context: .
      dockerfile: ./db/dockerfile
    container_name: database
    environment:
      - POSTGRES_USER=postgres
    ports:
      - "5432:5432"
    volumes:
      - volume:/var/lib/postgresql/data
    networks:
      - my_network
    restart: unless-stopped

networks:
  my_network:
    name: my_network
    driver: bridge

volumes:
  volume: