FROM postgres:15

ENV POSTGRES_USER=postgres
ENV POSTGRES_PASSWORD=postgres
ENV POSTGRES_DB=datacenter_management
ENV PGDATA=/var/lib/postgresql/data/pgdata

COPY database_setup.sql /docker-entrypoint-initdb.d/

# default PostgreSQL port
EXPOSE 5432

# storage location for PostgreSQL data
VOLUME ["/var/lib/postgresql/data"]

HEALTHCHECK --interval=30s --timeout=5s --start-period=5s --retries=3 \
  CMD pg_isready -U postgres || exit 1

